
RTFLAG = -MD  # link with dynamic runtime library
# RTFLAG = -MT  # link with static runtime library

MAKE_CMD = nmake -nologo -f Makefile.win32 RTFLAG=$(RTFLAG) ARM64EC=$(ARM64EC)

all:
	cd src/windows && $(MAKE_CMD)
	cd cmd && $(MAKE_CMD)

check: all
	cd tests && $(MAKE_CMD) check

clean:
	cd src/windows && $(MAKE_CMD) clean
	cd cmd && $(MAKE_CMD) clean
	cd tests && $(MAKE_CMD) clean
